### PR TITLE
LPS-117873 Provides a function called `updateEditingLanguageId` for updating `editingLanguageId` on FormProvider and clears some smells

### PR DESCRIPTION
**Pull request by diegonvs**
From: https://github.com/marcelabc/liferay-portal/pull/261

### What I did:

We couldn't set state directly from the layoutRendererInstance, for solving it, a function called `updateEditingLanguageId` was provided from `reactComponentRef`'s imperativeHandler and was used for causing an update on FormProvider.

Also, some weird typos/smells was fixed on the code.

### How to test my changes(Test Case):
0. Go to osgi/configs folder and create a file called `com.liferay.journal.web.internal.configuration.JournalDDMEditorConfiguration.config` and paste `useDataEngineEditor=B"true"` within.

1. Go to Content and Data -> Web Content -> Create a new Structure
2. Place a Rich Text field there
3. Name and Save the structure 
4. Go back to the Web Content Menu, create a web content with the recently created structure
5. Fill some values on the default language(probably will be 'en-us'), then, change to 'pt-br' and fill with translated data.
6. Switch between languages

#### What was happening:

The user wasn't able to see the filled translated values on the title and within the content when switching languages.

#### Now(with the fix):

The user is able to switch and see translated content with the selected language.

/cc @matuzalemsteles @leoadb @marcelabc @jeyvison

Do I need to left a warning on #z-engineering-latam-common-issues for people that probably are working on a similar issue?

### CODE REVIEW

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by alexcandidos** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by diegonvs** [comment]
Closing in favor of: https://github.com/oliveiraaraujo/liferay-portal/pull/63

I needed to update the commit messages with the correct ticket id and remove Leo's WIP

**Pull request closed without merging**
