### PR TITLE
LPS-100108 - Replace A.io with fetch

### PR DESCRIPTION
**Pull request by carloslancha**

### CODE REVIEW

**Comment by inacionery** [comment]
ci:test:sf

**Comment by inacionery** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by oliveiraaraujo** [comment]
Just started reviewing :)

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
sent to BChan at https://github.com/brianchandotcom/liferay-portal/pull/77672

**Comment by rafaprax** [comment]
ci:close

**Pull request closed without merging**
