### PR TITLE
LPS-109622 Add Observer.

### PR DESCRIPTION
**Pull request by oliveiraaraujo**

### CODE REVIEW

**Comment by oliveiraaraujo** [comment]
ci:test:sf

**Comment by oliveiraaraujo** [comment]
ci:test:relevant

**Comment by oliveiraaraujo** [comment]
ci:test:relevant

**Comment by alexcandidos** [comment]
ci:forward

**Comment by oliveiraaraujo** [comment]
ci:test:relevant

**Comment by oliveiraaraujo** [comment]
ci:stop

**Pull request closed without merging**
