### PR TITLE
LPS-98073 Create item selector url in backend

### PR DESCRIPTION
**Pull request by carloslancha**

### CODE REVIEW

**Comment by carloslancha** [comment]
cc @jbalsas @brunobasto

There are some little things that needs to be reviewed:

- ~~Randomly the component is not being rendered at the beginning, you need to cause a second render to do it appear (sending the form with the field mark as required, for example). I couldn't find the reason of this behavior.~~

- Description is not being validated. Automatic validation only happens on the image field, don't know if there's any mechanism on the framework to let it know that all the inputs on a field must be validated.

- Web Content Images Item Selector tab need to be properly configured, since I think is not pointing to the correct repository, so when you upload a picture you can't see it there (uploaded) if you open the item selector again.

- I'm not a java expert so please review all the backend stuff.

- Preview feature not implemented, that component doesn't exist yet.

- Review if all field properties are correctly set.

Thanks!

**Comment by brunobasto** [comment]
That was fast! Thank you, @carloslancha

**Comment by oliveiraaraujo** [comment]
Just started reviewing :)

**Comment by carloslancha** [comment]
@brunobasto @oliveiraaraujo  Fixed random rendering problem.

**Comment by oliveiraaraujo** [comment]
Just started reviewing :)

**Comment by oliveiraaraujo** [comment]
Just started reviewing :)

**Comment by oliveiraaraujo** [comment]
Pull request submitted to https://github.com/oliveiraaraujo/liferay-portal/pull/32. [See changes here.](https://github.com/oliveiraaraujo/liferay-portal/compare/133fbf8a250a~1...133fbf8a250a)

**Comment by oliveiraaraujo** [comment]
Pull request submitted to https://github.com/marcelabc/liferay-portal/pull/200. [See changes here.](https://github.com/oliveiraaraujo/liferay-portal/compare/fa38ce79d289~1...fa38ce79d289)

**Pull request closed without merging**
