### PR TITLE
LPS-117600 Fixes error when dropping a Field/FieldSet over another FieldSet

### PR DESCRIPTION
**Pull request by matuzalemsteles**
Fixed the error when dragging a Sidebar Field or FieldSet over a FieldSet. I also reverted a change added to `FormSupport` that was preventing the creating field groups.

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by alexcandidos** [comment]
ci:forward

**Comment by matuzalemsteles** [comment]
ci:forward

**Comment by alexcandidos** [comment]
Hi @matuzalemsteles , these failures are known issues according to @cvanut. He added some Forms tests to quarantine this morning (https://github.com/cvanut/liferay-portal/pull/62/files), so I believe we can ignore this failure for now and forward this commit to BChan.

cc: @jeyvison @natocesarrego

**Comment by matuzalemsteles** [comment]
Sent forward https://github.com/brianchandotcom/liferay-portal/pull/92043

**Pull request closed without merging**
