### PR TITLE
LPS-117686 implement endpoint to retrieve the context of the default data layout

### PR DESCRIPTION
**Pull request by jeyvison**
`
curl --location --request POST 'http://localhost:8080/o/data-engine/v2.0/data-definitions/38160/default-layout-context' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic dGVzdEBsaWZlcmF5LmNvbTp0ZXN0' \
--data-raw '{
    "containerId": "containerId",
    "dataDefinitionId": "38181",
    "dataRecordValues": {
    },
    "pathThemeImages": "http://localhost:8080/o/admin-theme/images",
    "namespace": "namespace",
    "readOnly": "false"
}'
`

### CODE REVIEW

**Comment by oliveiraaraujo** [comment]
Just started reviewing :)

**Comment by interaminense** [comment]
Just started reviewing :)

**Comment by interaminense** [comment]
Just started reviewing :)

**Comment by oliveiraaraujo** [comment]
Just started reviewing :)

**Pull request closed without merging**
