### PR TITLE
LPS-100099 Standardize Ajax requests in calendar-web

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by julien** [comment]
Hi @oliveiraaraujo,

We're currently replace `A.io.request` (and `A.io`) calls with `Liferay.Util.fetch`, so I thought I'd send you this PR for a quick review.

Thanks

**Comment by julien** [comment]
ci:test

**Comment by julien** [comment]
ci:test

**Comment by oliveiraaraujo** [comment]
ci:test:sf
ci:test:sf

**Comment by oliveiraaraujo** [comment]
ci:test:relevant

**Comment by oliveiraaraujo** [comment]
Pull request forwarded to https://github.com/phcp/liferay-portal/pull/27.

**Pull request closed without merging**
